M48
; DRILL file {KiCad 9.0.4} date 2025-11-29T15:55:59+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-29T15:55:59+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
%
G90
G05
T1
X3.5Y-2.595
T2
X3.3131Y-2.4137
X3.3131Y-2.7137
X3.9131Y-2.4137
X3.9131Y-2.7137
M30
